[package]
name = "app-server"
version.workspace = true
edition.workspace = true

[dependencies]
api-types = { workspace = true }
fixture = { workspace = true }
graph-core = { workspace = true }
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tower.workspace = true
http-body-util.workspace = true